-- Domain Watch Table - 域名监控/收藏表
CREATE TABLE `WEB_DOMAIN_WATCH` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `USER_ID` varchar(32) NOT NULL,
  `WATCH_CREATED_ON` date NULL COMMENT 'Creation date in WESITE_RETENTION_REPORTING_ZONE; NULL excludes unverified legacy rows',
  `DOMAIN_NAME` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(32),
  `REGISTRAR` varchar(255),
  `EXPIRY_DATE_TEXT` varchar(50),
  `EXPIRY_DATE` datetime,
  `NOTIFY_TYPE` smallint(1) DEFAULT '3',
  `LAST_NOTIFY_TIME` datetime,
  `LAST_CHECK_TIME` datetime,
  `REMARK` varchar(500),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_DOMAIN` (`USER_ID`, `DOMAIN_NAME`),
  KEY `IDX_USER_ID` (`USER_ID`),
  KEY `IDX_DOMAIN_WATCH_USER_CREATED_ON` (`USER_ID`, `WATCH_CREATED_ON`),
  KEY `IDX_EXPIRY_DATE` (`EXPIRY_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Domain Snapshot Table - WHOIS历史快照表
CREATE TABLE `WEB_DOMAIN_SNAPSHOT` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `DOMAIN_NAME` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(32),
  `REGISTRAR` varchar(255),
  `REGISTRAR_URL` varchar(500),
  `REGIST_CREATE_DATE_TEXT` varchar(50),
  `REGIST_UPDATE_DATE_TEXT` varchar(50),
  `REGIST_EXPIRY_DATE_TEXT` varchar(50),
  `DOMAIN_STATUS` varchar(500),
  `NAME_SERVERS` varchar(500),
  `DNSSEC` varchar(50),
  `REGISTRANT_ORG` varchar(255),
  `REGISTRANT_NAME` varchar(255),
  `REGISTRANT_COUNTRY` varchar(100),
  `REGISTRANT_STATE` varchar(100),
  `REGISTRANT_CITY` varchar(100),
  `REGISTRANT_EMAIL` varchar(255),
  `TECH_NAME` varchar(255),
  `TECH_EMAIL` varchar(255),
  `WHOIS_TEXT` mediumtext,
  `RDAP_TEXT` mediumtext,
  `SNAPSHOT_TIME` datetime NOT NULL,
  `SOURCE_IP` varchar(50),
  PRIMARY KEY (`ID`),
  KEY `IDX_DOMAIN_NAME` (`DOMAIN_NAME`),
  KEY `IDX_SNAPSHOT_TIME` (`SNAPSHOT_TIME`),
  KEY `IDX_DOMAIN_SNAPSHOT` (`DOMAIN_NAME`, `SNAPSHOT_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
