SELECT LOWER(TRIM(`EMAIL`)) AS NORMALIZED_EMAIL, COUNT(*) AS USER_COUNT
FROM `SYS_USER`
WHERE `EMAIL` IS NOT NULL AND TRIM(`EMAIL`) <> ''
GROUP BY LOWER(TRIM(`EMAIL`))
HAVING COUNT(*) > 1;

-- Stop here and resolve every returned row before executing the statements below.
UPDATE `SYS_USER`
SET `EMAIL` = LOWER(TRIM(`EMAIL`))
WHERE `EMAIL` IS NOT NULL;

ALTER TABLE `SYS_USER`
  DROP INDEX `IDX_USER_EMAIL`,
  MODIFY COLUMN `EMAIL` varchar(255) COLLATE utf8mb4_unicode_ci NULL,
  ADD UNIQUE KEY `IDX_USER_EMAIL` (`EMAIL`),
  ADD COLUMN `GOOGLE_SUB` varchar(255) COLLATE utf8mb4_bin NULL AFTER `EMAIL`,
  ADD UNIQUE KEY `IDX_USER_GOOGLE_SUB` (`GOOGLE_SUB`);
