CREATE TABLE `WEB_MONITOR_SNAPSHOT` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `WATCH_ID` varchar(32) NOT NULL,
  `CHECKED_AT` datetime NOT NULL,
  `STATE_JSON` mediumtext NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_MONITOR_SNAPSHOT_WATCH_CHECKED` (`WATCH_ID`, `CHECKED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `WEB_MONITOR_EVENT` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `WATCH_ID` varchar(32) NOT NULL,
  `SNAPSHOT_ID` varchar(32),
  `FINGERPRINT` varchar(128) NOT NULL,
  `EVENT_TYPE` varchar(64) NOT NULL,
  `OLD_VALUE` text,
  `NEW_VALUE` text,
  `OCCURRED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MONITOR_EVENT_WATCH_FINGERPRINT` (`WATCH_ID`, `FINGERPRINT`),
  KEY `IDX_MONITOR_EVENT_WATCH_OCCURRED` (`WATCH_ID`, `OCCURRED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `WEB_USER_NOTIFICATION` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `USER_ID` varchar(32) NOT NULL,
  `EVENT_ID` varchar(32) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `CONTENT` text,
  `TARGET_PATH` varchar(500) NOT NULL,
  `READ_AT` datetime,
  `EMAIL_STATE` varchar(32) NOT NULL DEFAULT 'pending',
  `EMAILED_AT` datetime,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_NOTIFICATION_USER_EVENT` (`USER_ID`, `EVENT_ID`),
  KEY `IDX_USER_NOTIFICATION_USER_READ_CREATED` (`USER_ID`, `READ_AT`, `CREATE_TIME`),
  KEY `IDX_USER_NOTIFICATION_EMAIL_CREATED` (`EMAIL_STATE`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `WEB_NOTIFICATION_PREFERENCE` (
  `ID` varchar(32) NOT NULL,
  `STATUS` smallint(1) DEFAULT '1',
  `DELETED` smallint(1) DEFAULT '0',
  `CREATE_BY` varchar(50),
  `CREATE_TIME` datetime,
  `UPDATE_BY` varchar(50),
  `UPDATE_TIME` datetime,
  `USER_ID` varchar(32) NOT NULL,
  `EMAIL_MODE` varchar(32) NOT NULL DEFAULT 'DAILY',
  `DOMAIN_EXPIRY_ENABLED` smallint(1) NOT NULL DEFAULT '1',
  `SSL_EXPIRY_ENABLED` smallint(1) NOT NULL DEFAULT '1',
  `DOMAIN_STATUS_ENABLED` smallint(1) NOT NULL DEFAULT '1',
  `DNS_CHANGE_ENABLED` smallint(1) NOT NULL DEFAULT '1',
  `WEBSITE_AVAILABILITY_ENABLED` smallint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_NOTIFICATION_PREFERENCE_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

ALTER TABLE `WEB_DOMAIN_WATCH_NOTIFY_LOG`
  ADD COLUMN `NOTIFICATION_ID` varchar(32) NULL AFTER `UPDATE_TIME`,
  ADD COLUMN `EVENT_ID` varchar(32) NULL AFTER `NOTIFICATION_ID`,
  ADD COLUMN `DELIVERY_MODE` varchar(32) NULL AFTER `EVENT_ID`,
  ADD COLUMN `SUBJECT` varchar(255) NULL AFTER `DELIVERY_MODE`,
  ADD KEY `IDX_NOTIFY_LOG_NOTIFICATION_MODE_RETRY` (`NOTIFICATION_ID`, `DELIVERY_MODE`, `RETRY_COUNT`),
  ADD KEY `IDX_NOTIFY_LOG_EVENT` (`EVENT_ID`);
