-- ============================================================
-- TLD Content Data - 30 Major TLDs
-- Generated: 2026-04-26
-- Insert into WEB_TLD_CONTENT
-- ============================================================

INSERT INTO `WEB_TLD_CONTENT` (`ID`,`TLD`,`INTRO_HTML`,`HISTORY_HTML`,`USE_CASES_HTML`,`FAMOUS_SITES_JSON`,`REGISTER_REQUIREMENTS_HTML`,`STATUS`,`DELETED`,`CREATE_BY`,`CREATE_TIME`) VALUES

('tld001','com',
'<p>The <strong>.com</strong> top-level domain is the most widely recognized and used domain extension in the world. Short for "commercial," it was originally intended for businesses but has become the default choice for virtually every type of website.</p><p>With over <strong>150 million registered .com domains</strong>, it remains the gold standard of internet addresses. A .com domain signals trust, authority, and global reach to visitors worldwide.</p>',
'<p>The .com TLD was one of the original six generic top-level domains (gTLDs) established in January 1985 by the Internet Assigned Numbers Authority (IANA). It was initially managed by the U.S. Department of Defense''s ARPANET project.</p><p>In 1993, <strong>Network Solutions</strong> received exclusive rights to manage .com registrations. In 1998, ICANN was created to oversee domain management, and .com was ultimately delegated to <strong>VeriSign</strong>, which continues to operate the registry today.</p>',
'<p>.com domains are used by every type of organization:</p><ul><li><strong>E-commerce stores</strong> — the #1 choice for online shops</li><li><strong>Corporate websites</strong> — professional business presence</li><li><strong>Startups &amp; SaaS</strong> — credibility with investors and customers</li><li><strong>Blogs &amp; media</strong> — personal brands and news sites</li><li><strong>Non-profits</strong> — .com is trusted even over .org by many users</li></ul>',
'[{"name":"Google","url":"google.com"},{"name":"Amazon","url":"amazon.com"},{"name":"Facebook","url":"facebook.com"},{"name":"YouTube","url":"youtube.com"},{"name":"Wikipedia","url":"wikipedia.com"},{"name":"Twitter","url":"twitter.com"},{"name":"Apple","url":"apple.com"},{"name":"Microsoft","url":"microsoft.com"}]',
'<p>There are <strong>no geographic or organizational restrictions</strong> on .com registrations. Anyone in the world can register a .com domain. Simply:</p><ul><li>Choose an available domain name</li><li>Register through any ICANN-accredited registrar</li><li>Typical cost: $8–$15/year</li></ul>',
1,0,'system',NOW()),

('tld002','net',
'<p>The <strong>.net</strong> top-level domain was originally created for network-related organizations, but today it is a versatile, globally recognized extension used across industries. It is the <strong>3rd most popular TLD</strong> with over 13 million registrations.</p><p>.net domains are trusted, authoritative, and a great alternative when your preferred .com is taken.</p>',
'<p>.net was one of the original six gTLDs launched in January 1985. It was intended for organizations involved in networking technologies, internet service providers, and infrastructure companies. Today, restrictions have been removed and it is open to all registrants.</p><p>Like .com, the .net registry is operated by <strong>VeriSign</strong>.</p>',
'<p>Common uses of .net domains include:</p><ul><li><strong>Internet service providers</strong> (ISPs) and hosting companies</li><li><strong>Tech companies and SaaS platforms</strong></li><li><strong>Alternative to .com</strong> when the .com is unavailable</li><li><strong>Developer tools and open source projects</strong></li><li><strong>Community and networking sites</strong></li></ul>',
'[{"name":"SlideShare","url":"slideshare.net"},{"name":"Over-blog","url":"over-blog.com"},{"name":"Speedtest","url":"speedtest.net"},{"name":"Internet Archive","url":"archive.org"}]',
'<p>No restrictions — open to anyone worldwide. Registration costs approximately <strong>$10–$15/year</strong> through any ICANN-accredited registrar.</p>',
1,0,'system',NOW()),

('tld003','org',
'<p>The <strong>.org</strong> top-level domain was established for non-profit organizations, but today it is open to any registrant. It carries a strong connotation of <strong>trust, mission-driven work, and community</strong>.</p><p>With over 10 million registrations, .org is the go-to choice for charities, foundations, open-source projects, and community organizations.</p>',
'<p>Launched as one of the original six gTLDs in January 1985, .org was intended for organizations that did not fit the .com or .net categories. The registry is now managed by the <strong>Public Interest Registry (PIR)</strong>, a non-profit organization itself.</p>',
'<p>Ideal for:</p><ul><li><strong>Non-profit organizations</strong> and charities</li><li><strong>Open-source software projects</strong> (Linux.org, Wikipedia.org)</li><li><strong>Religious institutions</strong></li><li><strong>Educational communities</strong></li><li><strong>Advocacy and activist groups</strong></li></ul>',
'[{"name":"Wikipedia","url":"wikipedia.org"},{"name":"Linux","url":"linux.org"},{"name":"Mozilla","url":"mozilla.org"},{"name":"Wikimedia","url":"wikimedia.org"},{"name":"Internet Archive","url":"archive.org"},{"name":"Craigslist","url":"craigslist.org"}]',
'<p>No restrictions — anyone can register a .org domain. Cost: approximately <strong>$10–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld004','io',
'<p>The <strong>.io</strong> domain extension has become one of the most popular choices for <strong>tech startups, SaaS products, developer tools, and gaming companies</strong>. It is the country code TLD (ccTLD) for the British Indian Ocean Territory, but its appeal comes from its association with "input/output" (I/O) in computer science.</p>',
'<p>.io is the country code TLD assigned to the British Indian Ocean Territory. While originally intended for that territory, it became widely adopted by the tech community in the 2010s due to its I/O association. It is now managed by the <strong>Internet Computer Bureau</strong> on behalf of the territory''s administrator.</p>',
'<p>.io domains are popular with:</p><ul><li><strong>Tech startups</strong> seeking a modern, tech-forward identity</li><li><strong>Developer tools</strong> (API services, CLI tools, IDEs)</li><li><strong>SaaS platforms</strong> targeting technical audiences</li><li><strong>Gaming companies</strong> (Agar.io, Slither.io)</li><li><strong>Open source projects</strong></li></ul>',
'[{"name":"GitHub","url":"github.io"},{"name":"Agar.io","url":"agar.io"},{"name":"Replit","url":"replit.com"},{"name":"CodePen","url":"codepen.io"}]',
'<p>No geographic restrictions for .io. Registration costs approximately <strong>$30–$60/year</strong>, higher than .com due to its premium positioning. Available through most major registrars.</p>',
1,0,'system',NOW()),

('tld005','ai',
'<p>The <strong>.ai</strong> domain extension has exploded in popularity with the rise of artificial intelligence. It is the ccTLD for <strong>Anguilla</strong>, a British Overseas Territory, but has been globally adopted by AI companies, machine learning startups, and tech innovators.</p>',
'<p>.ai was delegated to Anguilla in 1995. For years it remained a niche ccTLD, but the AI boom of the 2020s transformed it into one of the most sought-after domain extensions. The registry is managed by the <strong>Government of Anguilla</strong>.</p>',
'<p>Primary users of .ai:</p><ul><li><strong>Artificial intelligence companies</strong> and research labs</li><li><strong>Machine learning startups</strong></li><li><strong>AI-powered SaaS tools</strong></li><li><strong>Chatbots and voice assistants</strong></li><li><strong>Data science platforms</strong></li></ul>',
'[{"name":"OpenAI","url":"openai.com"},{"name":"Character.ai","url":"character.ai"},{"name":"Perplexity","url":"perplexity.ai"},{"name":"Stability AI","url":"stability.ai"}]',
'<p>Open to all registrants — no geographic restrictions. Due to high demand, .ai domains are priced at approximately <strong>$50–$100/year</strong>. Available at major registrars including Namecheap, GoDaddy, and Google Domains.</p>',
1,0,'system',NOW()),

('tld006','co',
'<p>The <strong>.co</strong> domain is the ccTLD for <strong>Colombia</strong>, but it is globally recognized as a shorter, modern alternative to .com. Its brevity and versatility make it ideal for companies, communities, and collaborations.</p>',
'<p>.co was assigned to Colombia but aggressively marketed internationally starting in 2010. The registry is managed by <strong>.CO Internet S.A.S.</strong> (now part of Neustar/GoDaddy). Twitter used t.co for URL shortening, which greatly boosted its global recognition.</p>',
'<p>Used by:</p><ul><li><strong>Startups</strong> that can''t get their .com</li><li><strong>Brands</strong> wanting a short, memorable URL</li><li><strong>Companies</strong> (the "co" in company)</li><li><strong>Communities and collectives</strong></li></ul>',
'[{"name":"AngelList","url":"angel.co"},{"name":"Product Hunt","url":"producthunt.com"},{"name":"t.co (Twitter)","url":"t.co"}]',
'<p>Open registration worldwide. Cost: approximately <strong>$25–$35/year</strong>.</p>',
1,0,'system',NOW()),

('tld007','app',
'<p>The <strong>.app</strong> domain is a modern gTLD specifically designed for <strong>mobile and web applications</strong>. It has built-in HTTPS requirement, meaning all .app domains must use SSL/TLS, making it one of the most secure TLDs available.</p>',
'<p>.app was launched by Google in 2018 as part of ICANN''s new gTLD program. Google acquired the rights for $25 million. The HTTPS requirement is enforced via HSTS preloading, making security a core feature of the TLD.</p>',
'<p>Perfect for:</p><ul><li><strong>Mobile apps</strong> with landing pages</li><li><strong>Web applications</strong> and SaaS products</li><li><strong>App developers and studios</strong></li><li><strong>Developer portfolios</strong></li></ul>',
'[{"name":"Robinhood","url":"robinhood.app"},{"name":"Linear","url":"linear.app"},{"name":"Craft","url":"craft.app"}]',
'<p>Open to all. All .app domains <strong>must use HTTPS</strong> (SSL required). Cost: approximately <strong>$15–$20/year</strong>.</p>',
1,0,'system',NOW()),

('tld008','dev',
'<p>The <strong>.dev</strong> domain is a Google-operated gTLD targeting <strong>developers and the development community</strong>. Like .app, it enforces HTTPS by default. It''s a natural fit for developer portfolios, open-source projects, and developer tools.</p>',
'<p>Launched by Google in 2019, .dev quickly gained traction in the developer community. It is also HSTS preloaded, requiring HTTPS for all websites. The registry is operated by <strong>Google Registry</strong>.</p>',
'<p>Ideal for:</p><ul><li><strong>Developer personal portfolios</strong></li><li><strong>Open source project pages</strong></li><li><strong>Developer tools and libraries</strong></li><li><strong>Tech blogs</strong> targeting developers</li></ul>',
'[{"name":"web.dev","url":"web.dev"},{"name":"Flutter","url":"flutter.dev"},{"name":"TensorFlow","url":"tensorflow.org"}]',
'<p>Open to anyone. HTTPS required. Cost: approximately <strong>$12–$18/year</strong>.</p>',
1,0,'system',NOW()),

('tld009','xyz',
'<p>The <strong>.xyz</strong> domain is one of the most popular new gTLDs, with over 4 million registrations. It is popular with startups, creatives, and anyone seeking a short, memorable domain that signals innovation and a break from convention.</p>',
'<p>Launched in 2014, .xyz was one of the first wave of new gTLDs under ICANN''s expansion program. It gained massive attention when <strong>Alphabet (Google''s parent company)</strong> used abc.xyz as its domain. The registry is operated by XYZ.COM LLC.</p>',
'<p>Common uses:</p><ul><li><strong>Startups and creative agencies</strong></li><li><strong>Personal portfolios</strong></li><li><strong>Experimental and side projects</strong></li><li><strong>Brand protection</strong> (securing .xyz alongside .com)</li></ul>',
'[{"name":"Alphabet (Google)","url":"abc.xyz"},{"name":"Classic.com","url":"classic.com"}]',
'<p>Open to all registrants worldwide. Very affordable at approximately <strong>$1–$5/year</strong> (promotional pricing common).</p>',
1,0,'system',NOW()),

('tld010','me',
'<p>The <strong>.me</strong> domain is the ccTLD for <strong>Montenegro</strong>, but it has been globally embraced as a personal domain extension — perfect for personal websites, portfolios, and individual branding.</p>',
'<p>Montenegro''s .me was delegated in 2007. The government partnered with <strong>doMEn</strong> and GoDaddy to market it internationally. It became synonymous with personal branding and individual identity online.</p>',
'<p>Popular with:</p><ul><li><strong>Personal websites and portfolios</strong></li><li><strong>Resume/CV domains</strong> (john.me, smith.me)</li><li><strong>Personal blogs</strong></li><li><strong>Freelancers and consultants</strong></li></ul>',
'[{"name":"About.me","url":"about.me"},{"name":"LastFM","url":"last.fm"}]',
'<p>Open to all. Cost: approximately <strong>$8–$20/year</strong>.</p>',
1,0,'system',NOW()),

('tld011','info',
'<p>The <strong>.info</strong> domain is a generic TLD originally created for <strong>informational websites</strong>. It is one of the original unrestricted gTLDs and remains a widely recognized option for knowledge bases, wikis, and information resources.</p>',
'<p>Launched in 2001 as part of ICANN''s first new gTLD round, .info was intended for informational sites. The registry is managed by <strong>Afilias</strong> (now Identity Digital). It has over 4 million registrations.</p>',
'<p>Common uses:</p><ul><li><strong>Information portals and knowledge bases</strong></li><li><strong>Government and public service information</strong></li><li><strong>Educational resources</strong></li><li><strong>Product/service information pages</strong></li></ul>',
'[{"name":"Camfrog","url":"camfrog.com"}]',
'<p>No restrictions. Cost: approximately <strong>$5–$10/year</strong>.</p>',
1,0,'system',NOW()),

('tld012','biz',
'<p>The <strong>.biz</strong> domain is a generic TLD specifically intended for <strong>business use</strong>. It is a professional alternative to .com for businesses unable to secure their preferred .com domain.</p>',
'<p>Launched in 2001, .biz was designed as a business-specific alternative to .com. It requires registrants to be businesses or organizations. The registry is managed by <strong>Afilias/Identity Digital</strong>.</p>',
'<p>Suited for:</p><ul><li><strong>Small businesses</strong> and local shops</li><li><strong>E-commerce stores</strong></li><li><strong>Professional services</strong></li></ul>',
'[]',
'<p>Intended for businesses — registrants should be using it for bona fide business purposes. Cost: approximately <strong>$10–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld013','online',
'<p>The <strong>.online</strong> domain is a popular new gTLD that clearly communicates an internet presence. It is perfect for any business, brand, or individual that wants to emphasize their digital-first identity.</p>',
'<p>Launched in 2015, .online quickly became one of the fastest-growing new gTLDs. It is managed by <strong>Radix</strong>. The extension''s intuitive meaning has driven strong adoption.</p>',
'<p>Ideal for:</p><ul><li><strong>Online businesses and e-commerce</strong></li><li><strong>Digital services</strong></li><li><strong>Course and learning platforms</strong></li><li><strong>Newsletters and media brands</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$3–$15/year</strong> (promotional pricing common).</p>',
1,0,'system',NOW()),

('tld014','store',
'<p>The <strong>.store</strong> domain is purpose-built for <strong>e-commerce and online retail</strong>. It immediately communicates that a website is a shop, making it one of the most relevant new gTLDs for merchants.</p>',
'<p>Launched in 2016 by <strong>Radix</strong>, .store has grown to hundreds of thousands of registrations. It is particularly popular with Shopify merchants and independent sellers.</p>',
'<p>Perfect for:</p><ul><li><strong>E-commerce and online shops</strong></li><li><strong>Retail brands</strong></li><li><strong>Drop-shipping stores</strong></li><li><strong>Digital product stores</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$5–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld015','tech',
'<p>The <strong>.tech</strong> domain is a popular new gTLD for <strong>technology companies, startups, and innovators</strong>. It is an ideal brand signal for the tech industry.</p>',
'<p>Launched in 2015 by <strong>Radix</strong>, .tech has become one of the fastest-growing tech-oriented TLDs. Events like CES and TechCrunch use it for campaign pages.</p>',
'<p>Used by:</p><ul><li><strong>Technology companies and startups</strong></li><li><strong>Tech conferences and events</strong></li><li><strong>Innovation labs</strong></li><li><strong>Technology blogs</strong></li></ul>',
'[{"name":"CES","url":"ces.tech"}]',
'<p>No restrictions. Cost: approximately <strong>$5–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld016','site',
'<p>The <strong>.site</strong> domain is a clean, versatile new gTLD suitable for any type of website. Its generic meaning makes it universally applicable.</p>',
'<p>Launched in 2015 by <strong>Radix</strong>. It is one of the most registered new gTLDs due to its intuitive meaning and affordable pricing.</p>',
'<p>Works for:</p><ul><li><strong>Personal and portfolio websites</strong></li><li><strong>Business websites</strong></li><li><strong>Landing pages</strong></li><li><strong>Community sites</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$3–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld017','shop',
'<p>The <strong>.shop</strong> domain is tailored for <strong>retail and e-commerce</strong>. Operated by GMO Registry, it is especially popular in Asia and with international e-commerce brands.</p>',
'<p>Launched in 2016 by <strong>GMO Registry</strong>, .shop saw rapid adoption in Japan and internationally. It competes directly with .store for e-commerce brands.</p>',
'<p>Ideal for:</p><ul><li><strong>Online shops and retailers</strong></li><li><strong>Brand microsites</strong></li><li><strong>Flash sale pages</strong></li></ul>',
'[]',
'<p>Open to all. Cost: approximately <strong>$20–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld018','club',
'<p>The <strong>.club</strong> domain is a community-focused new gTLD perfect for <strong>membership organizations, fan clubs, loyalty programs, and communities</strong>.</p>',
'<p>Launched in 2014, .club is managed by <strong>Registry Services LLC</strong>. It has grown to several hundred thousand registrations.</p>',
'<p>Used for:</p><ul><li><strong>Members-only communities</strong></li><li><strong>Fan clubs and interest groups</strong></li><li><strong>Loyalty programs</strong></li><li><strong>Sports clubs</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$5–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld019','blog',
'<p>The <strong>.blog</strong> domain is a clear, descriptive extension for <strong>bloggers, content creators, and publishers</strong>. It immediately signals the nature of the content.</p>',
'<p>Launched in 2017 by <strong>Knock Knock WHOIS There LLC</strong> (owned by Automattic, the company behind WordPress). It has grown steadily among WordPress bloggers and content creators.</p>',
'<p>Perfect for:</p><ul><li><strong>Personal blogs</strong></li><li><strong>Corporate blogs and thought leadership</strong></li><li><strong>Content creators</strong></li><li><strong>Niche topic blogs</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$20–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld020','news',
'<p>The <strong>.news</strong> domain is built for <strong>journalism, media companies, and news publishers</strong>. It clearly communicates a news-focused identity.</p>',
'<p>Launched in 2014 as part of ICANN''s new gTLD program, .news is managed by <strong>Midwest Internet Exchange, LLC (Tin Hat)</strong>.</p>',
'<p>Used by:</p><ul><li><strong>News websites and media companies</strong></li><li><strong>Local news outlets</strong></li><li><strong>Industry newsletters</strong></li><li><strong>Press release services</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$20–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld021','live',
'<p>The <strong>.live</strong> domain is popular with <strong>streaming platforms, live events, and real-time content</strong>. It conveys immediacy and live interaction.</p>',
'<p>Launched in 2015, .live is managed by <strong>United TLD Holdco Ltd.</strong> It has become popular with the streaming community.</p>',
'<p>Great for:</p><ul><li><strong>Live streaming channels</strong></li><li><strong>Sports and event broadcasting</strong></li><li><strong>Real-time services</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$15–$25/year</strong>.</p>',
1,0,'system',NOW()),

('tld022','world',
'<p>The <strong>.world</strong> domain conveys global reach and ambition. It is ideal for <strong>international organizations, global brands, and causes with worldwide impact</strong>.</p>',
'<p>Launched in 2015 by <strong>Binky Moon LLC (Donuts)</strong>, .world has been adopted by multinational organizations and global campaigns.</p>',
'<p>Used by:</p><ul><li><strong>International non-profits</strong></li><li><strong>Global brands and campaigns</strong></li><li><strong>Travel and geography sites</strong></li></ul>',
'[]',
'<p>No restrictions. Cost: approximately <strong>$20–$35/year</strong>.</p>',
1,0,'system',NOW()),

('tld023','tv',
'<p>The <strong>.tv</strong> domain is the ccTLD for <strong>Tuvalu</strong>, but has been globally adopted for <strong>television networks, streaming services, video content, and broadcasters</strong>.</p>',
'<p>Tuvalu''s .tv was delegated in 1996. In 2000, Tuvalu licensed .tv exclusively to <strong>dotTV (now VeriSign)</strong> for $50 million, transforming it into a globally marketed media domain.</p>',
'<p>Popular with:</p><ul><li><strong>TV networks and channels</strong></li><li><strong>Video streaming platforms</strong></li><li><strong>YouTube channels and video creators</strong></li><li><strong>Live streaming services</strong></li></ul>',
'[{"name":"Twitch","url":"twitch.tv"},{"name":"Justin.tv","url":"justin.tv"}]',
'<p>Open to all. Cost: approximately <strong>$30–$40/year</strong>.</p>',
1,0,'system',NOW()),

('tld024','us',
'<p>The <strong>.us</strong> domain is the official ccTLD for the <strong>United States of America</strong>. It is managed by <strong>Neustar (now GoDaddy)</strong> on behalf of the US government.</p>',
'<p>Delegated in 1985, .us was initially used by U.S. government and local entities. In 2002, it was opened for broader registration. It is popular for local businesses and government agencies wanting to emphasize American identity.</p>',
'<p>Used by:</p><ul><li><strong>U.S. businesses and brands</strong></li><li><strong>Local government agencies</strong></li><li><strong>American-focused services</strong></li></ul>',
'[]',
'<p>Restricted to <strong>U.S. citizens, residents, and entities</strong>. Cost: approximately <strong>$8–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld025','eu',
'<p>The <strong>.eu</strong> domain is the official ccTLD for the <strong>European Union</strong>. It represents European identity, trust, and GDPR compliance.</p>',
'<p>Launched in 2006 by <strong>EURid</strong> (European Registry for Internet Domains), .eu quickly amassed over 3 million registrations. It is one of the most successful regional TLDs.</p>',
'<p>Used by:</p><ul><li><strong>EU-based businesses</strong></li><li><strong>EU institutions and organizations</strong></li><li><strong>Pan-European projects</strong></li><li><strong>Companies targeting European customers</strong></li></ul>',
'[{"name":"EU Parliament","url":"europarl.europa.eu"}]',
'<p>Restricted to <strong>EU citizens, residents, and organizations</strong> based in EU member states. Cost: approximately <strong>$10–$15/year</strong>.</p>',
1,0,'system',NOW()),

('tld026','cc',
'<p>The <strong>.cc</strong> domain is the ccTLD for the <strong>Cocos (Keeling) Islands</strong>, but is widely used as a generic domain — interpreted as "company," "commerce," or "credit card." It is a popular two-letter alternative to .com.</p>',
'<p>Delegated to the Cocos Islands and commercially operated globally by <strong>VeriSign</strong>. It has been actively marketed as an open TLD since the late 1990s.</p>',
'<p>Popular for:</p><ul><li><strong>Short brand URLs</strong></li><li><strong>Alternative to .com</strong></li><li><strong>Creative industry professionals</strong></li></ul>',
'[]',
'<p>Open to all worldwide. Cost: approximately <strong>$20–$30/year</strong>.</p>',
1,0,'system',NOW()),

('tld027','in',
'<p>The <strong>.in</strong> domain is the official ccTLD for <strong>India</strong>, the world''s most populous country and a rapidly growing digital economy. With over 2 million registrations, .in is one of Asia''s most active ccTLDs.</p>',
'<p>Delegated in 1989, .in is managed by <strong>INRegistry</strong> (operated by NIXI). India''s tech boom and digital growth have made .in increasingly relevant globally.</p>',
'<p>Used by:</p><ul><li><strong>Indian businesses and startups</strong></li><li><strong>Indian government portals</strong></li><li><strong>Global companies targeting the Indian market</strong></li></ul>',
'[{"name":"IRCTC","url":"irctc.co.in"},{"name":"Flipkart","url":"flipkart.com"}]',
'<p>Open to Indian residents and entities. Cost: approximately <strong>$5–$10/year</strong>.</p>',
1,0,'system',NOW()),

('tld028','de',
'<p>The <strong>.de</strong> domain is the official ccTLD for <strong>Germany</strong>. With over <strong>17 million registrations</strong>, it is the largest national ccTLD in the world, surpassing even many generic TLDs.</p>',
'<p>Delegated in 1986, .de is managed by <strong>DENIC eG</strong>, a cooperative of internet service providers. Germany''s strong economy and internet infrastructure have made .de one of the world''s most trusted country domains.</p>',
'<p>Used by:</p><ul><li><strong>German businesses of all sizes</strong></li><li><strong>Government and educational institutions</strong></li><li><strong>International companies targeting German customers</strong></li></ul>',
'[{"name":"SPIEGEL","url":"spiegel.de"},{"name":"BILD","url":"bild.de"},{"name":"Deutsche Bahn","url":"bahn.de"}]',
'<p>No geographic restriction — anyone can register .de. However, a <strong>local administrative contact in Germany</strong> may be required by some registrars. Cost: approximately <strong>$5–$10/year</strong>.</p>',
1,0,'system',NOW()),

('tld029','uk',
'<p>The <strong>.uk</strong> domain (and its subdomain <strong>.co.uk</strong>) is the official ccTLD for the <strong>United Kingdom</strong>. .co.uk is the traditional commercial domain used by UK businesses.</p>',
'<p>The .uk TLD was delegated in 1985, managed by <strong>Nominet UK</strong>. The direct second-level .uk was opened to the public in 2014, allowing registrations without the .co.uk prefix.</p>',
'<p>Used by:</p><ul><li><strong>UK businesses</strong></li><li><strong>British media and news</strong></li><li><strong>UK government services</strong></li><li><strong>International companies with UK presence</strong></li></ul>',
'[{"name":"BBC","url":"bbc.co.uk"},{"name":"The Guardian","url":"theguardian.com"},{"name":"Amazon UK","url":"amazon.co.uk"}]',
'<p>No nationality restrictions — anyone can register .uk. Cost: approximately <strong>£7–£10/year</strong> (~$8–$12).</p>',
1,0,'system',NOW());
